# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-05 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_userinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='status',
            field=models.IntegerField(choices=[(1, '本科'), (2, '专科'), (3, '高中'), (4, '初中')], default=1, verbose_name='学历'),
        ),
    ]
