# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-06 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20181205_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=32, verbose_name='设备名称')),
                ('device_class', models.CharField(max_length=32, verbose_name='设备类别')),
                ('device_group', models.CharField(max_length=32, verbose_name='设备组')),
                ('device_course', models.CharField(max_length=32, verbose_name='品牌')),
                ('device_ip', models.GenericIPAddressField(verbose_name='ip地址')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='启用时间')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='报废时间')),
                ('device_status', models.IntegerField(blank=True, choices=[(1, '开机'), (2, '待料'), (3, '报警'), (4, '待维修')], null=True, verbose_name='设备状态')),
                ('use_status', models.IntegerField(blank=True, choices=[(1, '开机'), (2, '待料'), (3, '报警'), (4, '待维修')], null=True, verbose_name='使用状态')),
            ],
        ),
        migrations.RemoveField(
            model_name='classlist',
            name='course',
        ),
        migrations.RemoveField(
            model_name='classlist',
            name='school',
        ),
        migrations.RemoveField(
            model_name='classlist',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='classlist',
            name='tutor',
        ),
        migrations.DeleteModel(
            name='ClassList',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
