# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-08 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20181207_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pruduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.IntegerField(verbose_name='物料编码')),
                ('material_name', models.CharField(max_length=32, verbose_name='物料名称')),
                ('product_type', models.CharField(max_length=32, verbose_name='规格型号')),
                ('unit', models.CharField(max_length=32, verbose_name='单位')),
                ('workorder_code', models.IntegerField(verbose_name='工单编码')),
                ('product_order', models.IntegerField(verbose_name='生产订单数')),
                ('workorder_startdate', models.DateField(blank=True, null=True, verbose_name='工单日期')),
                ('workorder_status', models.IntegerField(blank=True, choices=[(1, '开立'), (2, '关闭')], null=True, verbose_name='工单状态')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Department', verbose_name='部门名称')),
            ],
        ),
    ]
