# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-08 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20181208_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='depart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.Department', verbose_name='部门名称'),
        ),
    ]
