# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-09 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20181208_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='number',
            field=models.IntegerField(default=1, verbose_name='工号'),
            preserve_default=False,
        ),
    ]
