# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-09 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20181209_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tools',
            name='toolholder',
        ),
        migrations.AddField(
            model_name='tools',
            name='diameter',
            field=models.IntegerField(default=1, verbose_name='直径/mm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tools',
            name='tool_butoom',
            field=models.IntegerField(verbose_name='刀刃长/mm'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='tool_top',
            field=models.IntegerField(verbose_name='刀柄长/mm'),
        ),
    ]
