# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-10 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_auto_20181209_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkInProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.IntegerField(verbose_name='物料编码')),
                ('material_name', models.CharField(max_length=32, verbose_name='物料名称')),
                ('product_type', models.CharField(max_length=32, verbose_name='规格型号')),
                ('unit', models.CharField(max_length=32, verbose_name='单位')),
                ('early_balance', models.IntegerField(verbose_name='前期结存')),
                ('incoming_material', models.IntegerField(verbose_name='来料数量')),
                ('job_booking', models.IntegerField(verbose_name='报工数量')),
                ('wip', models.IntegerField(verbose_name='生产在制数量')),
                ('good_products', models.IntegerField(verbose_name='良品数')),
                ('bad_products', models.IntegerField(verbose_name='不良品数')),
                ('depart', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.Department', verbose_name='部门名称')),
            ],
        ),
        migrations.AlterField(
            model_name='tools',
            name='number',
            field=models.IntegerField(verbose_name='使用寿命'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='warehouse',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='crm.Warehouse', verbose_name='仓库名称'),
        ),
    ]
