# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-10 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_auto_20181210_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinproduct',
            name='putinstorage',
            field=models.IntegerField(default=1, verbose_name='入库数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workinproduct',
            name='unputinstorage',
            field=models.IntegerField(default=1, verbose_name='未入库数'),
            preserve_default=False,
        ),
    ]
