# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-05 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20181205_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='parent',
            new_name='group_menu',
        ),
    ]
